name: AdvancedPet
main: fr.nocsy.almpet.AdvancedPet
version: 0.2.1
description: Plugin made by Nocsy
depends: [WorldGuard, MythicMobs, ModelEngine vR2.2.0]
author: Nocsy
api-version: 1.16
commands:
  advancedpet:
    description: Command to manage your pets
    Usage: /advancedpet